# OPTIONAL: Example workflow to add to your other repositories
# Copy this to .github/workflows/notify-website.yml in your other repos
# NOTE: Requires cross-repo-trigger.yml to be enabled on the website

name: Notify Website of Updates

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  # When repo is starred
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository info
      id: repo_info
      run: |
        echo "stars=$(gh api repos/${{ github.repository }} --jq .stargazers_count)" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger website update
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEBSITE_TRIGGER_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/nshkrdotcom/nshkrdotcom.github.io/dispatches \
          -d '{"event_type":"external-repo-updated","client_payload":{"repository":"${{ github.event.repository.name }}","event_type":"${{ github.event_name }}","stars":"${{ steps.repo_info.outputs.stars }}"}}'