name: Update Repository Star Counts

on:
  # Runs every hour
  schedule:
    - cron: '0 * * * *'
    
  # Allows manual triggering from Actions tab
  workflow_dispatch:
  
  # OPTIONAL TRIGGERS (uncomment to enable):
  
  # # Runs on pushes to main branch
  # push:
  #   branches: [ main ]
  
  # # Triggers when a repository is starred/unstarred
  # watch:
  #   types: [started]
    
  # # Triggers on repository creation/deletion/update
  # repository_dispatch:
  #   types: [repo-updated]

jobs:
  update-star-counts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        
    - name: Setup GitHub CLI
      run: |
        # GitHub CLI is pre-installed on GitHub-hosted runners
        gh --version
        
    - name: Make scripts executable
      run: |
        chmod +x ./scripts/update_hugo_data.sh
        
    - name: Fetch and update Hugo data
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching latest repository star counts..."
        ./scripts/update_hugo_data.sh
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changed
      if: steps.verify-changed-files.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/repos.yml
        git commit -m "🤖 Auto-update repository star counts"
        git push
        
    - name: Trigger Hugo deployment
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        gh workflow run hugo-deploy.yml
      env:
        GH_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}